FPT_SEM4/App_WebRuou/Controllers/PaymentController.cs
using App_WebRuou.Models;
using App_WebRuou.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace App_WebRuou.Controllers
{
    public class PaymentController : Controller
    {
        private readonly IPayPalService _payPalService;

        public PaymentController(IPayPalService payPalService)
        {
            _payPalService = payPalService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> CreatePaymentUrl(PaymentInformationModel model)
        {
            var url = await _payPalService.CreatePaymentUrl(model, HttpContext);

            return Redirect(url);
        }

        public IActionResult PaymentCallback()
        {
            var response = _payPalService.PaymentExecute(Request.Query);
            if (response.Success == true)
            {
                return RedirectToAction("ThanhToan", "KhachHang", new { pttt = "PayPal" });
            }
            else
            {
                return RedirectToAction("ThanhToan", "KhachHang", new { pttt = "Huy" });
            }
        }

    }
}

FPT_SEM4/App_WebRuou/Views/Payment/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<div class="container">
    <div class="page-content">
        <div class="text-center">
            <h1 class="display-4">Thanh toán PayPal tại <a href="https://code-mega.com">Code Mega</a></h1>
            <p>Learn about <a href="https://code-mega.com">building Web apps with ASP.NET Core</a>.</p>
        </div>

        <div class="table-responsive">
@*            <form action="/Payment/CreatePaymentUrl" id="frmCreateOrder" method="POST">*@
            <form asp-action="CreatePaymentUrl" asp-controller="Payment" id="frmCreateOrder" method="POST">
                <div class="form-group">
                    <label for="ordertype">Loại hàng hóa </label>
                    <select name="OrderType" id="ordertype" class="form-control">
                        <option value="electric">Đồ điện tử</option>
                        <option value="fashion">Thời trang</option>
                        <option value="other">Khác</option>
                    </select>
                </div>
                <br />
                <div class="form-group">
                    <label for="Name">Tên khách hàng</label>
                    <input class="form-control"
                           id="Name"
                           name="Name"
                           type="text"
                           value="Code Mega">
                </div>
                <br />
                <div class="form-group">
                    <label for="Amount">Số tiền</label>
                    <input class="form-control"
                           id="Amount"
                           name="Amount"
                           type="text"
                           value="2000">
                </div>
                <br />
                <div class="form-group">
                    <label for="OrderDescription">Nội dung thanh toán</label>
                    <textarea class="form-control"
                              cols="20"
                              id="OrderDescription"
                              name="OrderDescription"
                              rows="2">Thanh toán tại Code Mega</textarea>
                </div>
                <br />
                <button type="submit" class="btn btn-primary">Thanh toán (Checkout)</button>
            </form>
        </div>
    </div>
</div>